spring:
  server:
    port: 8080
  application:
    name: backend

  # database config
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # h2 config
  h2:
    console:
      enabled: true

  # jpa config
  jpa:
    hibernate:
      ddl-auto: create
    # show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

  # security oauth2 config
  security:
    oauth2:
      client:
        # 인증 제공자 설정
        provider:
          naver:
            # 사용자가 네이버 로그인 페이지로 리다이렉트될 주소
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            # 엑세스 토큰 발급 url
            token-uri: https://nid.naver.com/oauth2.0/token
            # 인증된 사용자 정보를 가져오는 url
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 사용자 정보 응답에서 사용자 식별자로 사용할 속성(naver = id)
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub # 구글의 고유 ID
        # 클라이언트 애플리케이션 설정
        registration:
          naver:
            client-id: BUCJIyUlA6xJ4fyVWMXX # required
            client-secret: jLaK_LSfJ8 # required
            redirect-uri: http://localhost:8080/api/auth/callback/naver
            # 클라이언트가 엑세스 토큰을 얻기 위해 사용하는 방법
            authorization-grant-type: authorization_code
            # 클라이언트가 서버에 자신을 인증하는 방법
            client-authentication-method: client_secret_post
            client-name: naver
            scope:
              - email
              - profile
          google:
            client-id: 1095063717762-4spaqlqe0nv0gup5hlc8ske3qb17de31.apps.googleusercontent.com # required
            client-secret: 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 # required
            redirect-uri: http://localhost:8080/api/auth/callback/google
            authorization-grant-type: authorization_code
            scope:
              - openid
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email

# aws
cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: public-search-s3

# jwt secret
jwt:
  secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yanR3dG9rZW5nZW5lcmF0aW9uYW5kc2hvdWxkYmVsb25nZXJ0aGFuNjRjaGFyYWN0ZXJz
  expiration: 360000

